#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application="parallelCommTest"

# Mesh generation
blockMesh

# Domain decomposition
decomposePar

# mpirun
mpirun -np 4 parallelLoopTest -parallel
